runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

# Service name is optional and is used to manage different services within the same project.
# service: your-service-name

# env_variables:
#   NODE_ENV: production

# handlers:
#   - url: /.*
#     script: auto
#     secure: always
